[package]
name = "ocr"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
image = "0.25"
imageproc = "0.25"
rust-paddle-ocr = { git = "https://github.com/zibo-chen/rust-paddle-ocr.git" }
